require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CostCentersController do

  # This should return the minimal set of attributes required to create a valid
  # CostCenter. As you add validations to CostCenter, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "cost_center" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CostCentersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all cost_centers as @cost_centers" do
      cost_center = CostCenter.create! valid_attributes
      get :index, {}, valid_session
      assigns(:cost_centers).should eq([cost_center])
    end
  end

  describe "GET show" do
    it "assigns the requested cost_center as @cost_center" do
      cost_center = CostCenter.create! valid_attributes
      get :show, {:id => cost_center.to_param}, valid_session
      assigns(:cost_center).should eq(cost_center)
    end
  end

  describe "GET new" do
    it "assigns a new cost_center as @cost_center" do
      get :new, {}, valid_session
      assigns(:cost_center).should be_a_new(CostCenter)
    end
  end

  describe "GET edit" do
    it "assigns the requested cost_center as @cost_center" do
      cost_center = CostCenter.create! valid_attributes
      get :edit, {:id => cost_center.to_param}, valid_session
      assigns(:cost_center).should eq(cost_center)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CostCenter" do
        expect {
          post :create, {:cost_center => valid_attributes}, valid_session
        }.to change(CostCenter, :count).by(1)
      end

      it "assigns a newly created cost_center as @cost_center" do
        post :create, {:cost_center => valid_attributes}, valid_session
        assigns(:cost_center).should be_a(CostCenter)
        assigns(:cost_center).should be_persisted
      end

      it "redirects to the created cost_center" do
        post :create, {:cost_center => valid_attributes}, valid_session
        response.should redirect_to(CostCenter.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cost_center as @cost_center" do
        # Trigger the behavior that occurs when invalid params are submitted
        CostCenter.any_instance.stub(:save).and_return(false)
        post :create, {:cost_center => { "cost_center" => "invalid value" }}, valid_session
        assigns(:cost_center).should be_a_new(CostCenter)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CostCenter.any_instance.stub(:save).and_return(false)
        post :create, {:cost_center => { "cost_center" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested cost_center" do
        cost_center = CostCenter.create! valid_attributes
        # Assuming there are no other cost_centers in the database, this
        # specifies that the CostCenter created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CostCenter.any_instance.should_receive(:update_attributes).with({ "cost_center" => "MyString" })
        put :update, {:id => cost_center.to_param, :cost_center => { "cost_center" => "MyString" }}, valid_session
      end

      it "assigns the requested cost_center as @cost_center" do
        cost_center = CostCenter.create! valid_attributes
        put :update, {:id => cost_center.to_param, :cost_center => valid_attributes}, valid_session
        assigns(:cost_center).should eq(cost_center)
      end

      it "redirects to the cost_center" do
        cost_center = CostCenter.create! valid_attributes
        put :update, {:id => cost_center.to_param, :cost_center => valid_attributes}, valid_session
        response.should redirect_to(cost_center)
      end
    end

    describe "with invalid params" do
      it "assigns the cost_center as @cost_center" do
        cost_center = CostCenter.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CostCenter.any_instance.stub(:save).and_return(false)
        put :update, {:id => cost_center.to_param, :cost_center => { "cost_center" => "invalid value" }}, valid_session
        assigns(:cost_center).should eq(cost_center)
      end

      it "re-renders the 'edit' template" do
        cost_center = CostCenter.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CostCenter.any_instance.stub(:save).and_return(false)
        put :update, {:id => cost_center.to_param, :cost_center => { "cost_center" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cost_center" do
      cost_center = CostCenter.create! valid_attributes
      expect {
        delete :destroy, {:id => cost_center.to_param}, valid_session
      }.to change(CostCenter, :count).by(-1)
    end

    it "redirects to the cost_centers list" do
      cost_center = CostCenter.create! valid_attributes
      delete :destroy, {:id => cost_center.to_param}, valid_session
      response.should redirect_to(cost_centers_url)
    end
  end

end
