require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FormOfPaymentsController do

  # This should return the minimal set of attributes required to create a valid
  # FormOfPayment. As you add validations to FormOfPayment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FormOfPaymentsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all form_of_payments as @form_of_payments" do
      form_of_payment = FormOfPayment.create! valid_attributes
      get :index, {}, valid_session
      assigns(:form_of_payments).should eq([form_of_payment])
    end
  end

  describe "GET show" do
    it "assigns the requested form_of_payment as @form_of_payment" do
      form_of_payment = FormOfPayment.create! valid_attributes
      get :show, {:id => form_of_payment.to_param}, valid_session
      assigns(:form_of_payment).should eq(form_of_payment)
    end
  end

  describe "GET new" do
    it "assigns a new form_of_payment as @form_of_payment" do
      get :new, {}, valid_session
      assigns(:form_of_payment).should be_a_new(FormOfPayment)
    end
  end

  describe "GET edit" do
    it "assigns the requested form_of_payment as @form_of_payment" do
      form_of_payment = FormOfPayment.create! valid_attributes
      get :edit, {:id => form_of_payment.to_param}, valid_session
      assigns(:form_of_payment).should eq(form_of_payment)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new FormOfPayment" do
        expect {
          post :create, {:form_of_payment => valid_attributes}, valid_session
        }.to change(FormOfPayment, :count).by(1)
      end

      it "assigns a newly created form_of_payment as @form_of_payment" do
        post :create, {:form_of_payment => valid_attributes}, valid_session
        assigns(:form_of_payment).should be_a(FormOfPayment)
        assigns(:form_of_payment).should be_persisted
      end

      it "redirects to the created form_of_payment" do
        post :create, {:form_of_payment => valid_attributes}, valid_session
        response.should redirect_to(FormOfPayment.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved form_of_payment as @form_of_payment" do
        # Trigger the behavior that occurs when invalid params are submitted
        FormOfPayment.any_instance.stub(:save).and_return(false)
        post :create, {:form_of_payment => { "name" => "invalid value" }}, valid_session
        assigns(:form_of_payment).should be_a_new(FormOfPayment)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        FormOfPayment.any_instance.stub(:save).and_return(false)
        post :create, {:form_of_payment => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested form_of_payment" do
        form_of_payment = FormOfPayment.create! valid_attributes
        # Assuming there are no other form_of_payments in the database, this
        # specifies that the FormOfPayment created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        FormOfPayment.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => form_of_payment.to_param, :form_of_payment => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested form_of_payment as @form_of_payment" do
        form_of_payment = FormOfPayment.create! valid_attributes
        put :update, {:id => form_of_payment.to_param, :form_of_payment => valid_attributes}, valid_session
        assigns(:form_of_payment).should eq(form_of_payment)
      end

      it "redirects to the form_of_payment" do
        form_of_payment = FormOfPayment.create! valid_attributes
        put :update, {:id => form_of_payment.to_param, :form_of_payment => valid_attributes}, valid_session
        response.should redirect_to(form_of_payment)
      end
    end

    describe "with invalid params" do
      it "assigns the form_of_payment as @form_of_payment" do
        form_of_payment = FormOfPayment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FormOfPayment.any_instance.stub(:save).and_return(false)
        put :update, {:id => form_of_payment.to_param, :form_of_payment => { "name" => "invalid value" }}, valid_session
        assigns(:form_of_payment).should eq(form_of_payment)
      end

      it "re-renders the 'edit' template" do
        form_of_payment = FormOfPayment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FormOfPayment.any_instance.stub(:save).and_return(false)
        put :update, {:id => form_of_payment.to_param, :form_of_payment => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested form_of_payment" do
      form_of_payment = FormOfPayment.create! valid_attributes
      expect {
        delete :destroy, {:id => form_of_payment.to_param}, valid_session
      }.to change(FormOfPayment, :count).by(-1)
    end

    it "redirects to the form_of_payments list" do
      form_of_payment = FormOfPayment.create! valid_attributes
      delete :destroy, {:id => form_of_payment.to_param}, valid_session
      response.should redirect_to(form_of_payments_url)
    end
  end

end
