require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ShoppingsController do

  # This should return the minimal set of attributes required to create a valid
  # Shopping. As you add validations to Shopping, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "supplier" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ShoppingsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all shoppings as @shoppings" do
      shopping = Shopping.create! valid_attributes
      get :index, {}, valid_session
      assigns(:shoppings).should eq([shopping])
    end
  end

  describe "GET show" do
    it "assigns the requested shopping as @shopping" do
      shopping = Shopping.create! valid_attributes
      get :show, {:id => shopping.to_param}, valid_session
      assigns(:shopping).should eq(shopping)
    end
  end

  describe "GET new" do
    it "assigns a new shopping as @shopping" do
      get :new, {}, valid_session
      assigns(:shopping).should be_a_new(Shopping)
    end
  end

  describe "GET edit" do
    it "assigns the requested shopping as @shopping" do
      shopping = Shopping.create! valid_attributes
      get :edit, {:id => shopping.to_param}, valid_session
      assigns(:shopping).should eq(shopping)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Shopping" do
        expect {
          post :create, {:shopping => valid_attributes}, valid_session
        }.to change(Shopping, :count).by(1)
      end

      it "assigns a newly created shopping as @shopping" do
        post :create, {:shopping => valid_attributes}, valid_session
        assigns(:shopping).should be_a(Shopping)
        assigns(:shopping).should be_persisted
      end

      it "redirects to the created shopping" do
        post :create, {:shopping => valid_attributes}, valid_session
        response.should redirect_to(Shopping.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved shopping as @shopping" do
        # Trigger the behavior that occurs when invalid params are submitted
        Shopping.any_instance.stub(:save).and_return(false)
        post :create, {:shopping => { "supplier" => "invalid value" }}, valid_session
        assigns(:shopping).should be_a_new(Shopping)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Shopping.any_instance.stub(:save).and_return(false)
        post :create, {:shopping => { "supplier" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested shopping" do
        shopping = Shopping.create! valid_attributes
        # Assuming there are no other shoppings in the database, this
        # specifies that the Shopping created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Shopping.any_instance.should_receive(:update_attributes).with({ "supplier" => "MyString" })
        put :update, {:id => shopping.to_param, :shopping => { "supplier" => "MyString" }}, valid_session
      end

      it "assigns the requested shopping as @shopping" do
        shopping = Shopping.create! valid_attributes
        put :update, {:id => shopping.to_param, :shopping => valid_attributes}, valid_session
        assigns(:shopping).should eq(shopping)
      end

      it "redirects to the shopping" do
        shopping = Shopping.create! valid_attributes
        put :update, {:id => shopping.to_param, :shopping => valid_attributes}, valid_session
        response.should redirect_to(shopping)
      end
    end

    describe "with invalid params" do
      it "assigns the shopping as @shopping" do
        shopping = Shopping.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Shopping.any_instance.stub(:save).and_return(false)
        put :update, {:id => shopping.to_param, :shopping => { "supplier" => "invalid value" }}, valid_session
        assigns(:shopping).should eq(shopping)
      end

      it "re-renders the 'edit' template" do
        shopping = Shopping.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Shopping.any_instance.stub(:save).and_return(false)
        put :update, {:id => shopping.to_param, :shopping => { "supplier" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested shopping" do
      shopping = Shopping.create! valid_attributes
      expect {
        delete :destroy, {:id => shopping.to_param}, valid_session
      }.to change(Shopping, :count).by(-1)
    end

    it "redirects to the shoppings list" do
      shopping = Shopping.create! valid_attributes
      delete :destroy, {:id => shopping.to_param}, valid_session
      response.should redirect_to(shoppings_url)
    end
  end

end
